environment: uat
hdfs_uri: hdfs://ns1
ofs_uri: ofs://ozone1782570080
hms_host: ccycloud-1.jshin-sbi.root.comops.site
hms_hosts: ccycloud-1.jshin-sbi.root.comops.site,ccycloud-6.jshin-sbi.root.comops.site
hms_uris: thrift://ccycloud-1.jshin-sbi.root.comops.site:9083,thrift://ccycloud-6.jshin-sbi.root.comops.site:9083
hms_port: "9083"
krb_realm: ${KRB_REALM}
ozone_om_service_id: ozone1782570080
ozone_om_address: ccycloud-2.jshin-sbi.root.comops.site:9862,ccycloud-8.jshin-sbi.root.comops.site:9862
warehouse_base: ofs://ozone1782570080/uat/data
yarn_queue_default: etl

authorization:
  model: ranger
  principal: systest@${KRB_REALM}
  policy_inventory: governance/configs/security/ranger.yaml
  doc: docs/operations/ranger-authorization.md
  forbidden: [chmod, chown, setfacl, hdfs_dfs_chmod, ozone_native_acl]

cluster:
  total_vcores: 26496
  total_memory_gb: 123566
  node_managers: 214
  cores_per_node: 124
  memory_per_node_gb: 577
  yarn_reserved_ratio: 0.10

resource_limits:
  max_executors_absolute: 100
  max_executor_cores: 6
  executor_memory: "8g"
  executor_memory_overhead: "2g"
  driver_memory: "4g"
  driver_cores: 2
  shuffle_partitions: 200

medallion:
  hdfs_raw_path: hdfs://ns1/uat/raw/financial/transactions
  brnz_base: ofs://ozone1782570080/uat/data/brnz
  slvr_base: ofs://ozone1782570080/uat/data/slvr
  gld_base: ofs://ozone1782570080/uat/data/gld
  table_suffixes:
    brnz: transactions
    slvr: transactions
    gld: daily_transaction_report
